var funcs = require("./funcs.js");
var div = require ("./localvars.js");
var jq = require("./jq.js");
var iter = require("./iterative1.js");
console.log(funcs);
funcs.cat();
div.divide();
funcs.dog();
jq.title();
iter.bam();
